#!/bin/sh
echo "broadcast: ";
ifconfig en0 | grep broadcast | cut -f6 -d' ' | tr ' ' '\n';
echo "\nAutres adresses du sous-reseau:";
ping -t 1 10.1.255.255 | grep from | cut -f4 -d' ' | tr -d ':' | sort;
